name: clean

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 22 3 *'  # 12:00 AM on March 22
    - cron: '0 0 22 6 *'  # 12:00 AM on June 22
    - cron: '0 0 22 9 *'  # 12:00 AM on September 22
    - cron: '0 0 22 12 *' # 12:00 AM on December 22

jobs:
  clean:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' && github.event_name != 'pull_request'

    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      R_KEEP_PKG_SOURCE: yes

    steps:
      - name: Check out the staging universe.
        uses: actions/checkout@v4

      - name: Remove config.json.
        run: rm -f config.json

      - name: Commit and push changes.
        run: |
          if git diff --quiet && git diff --staged --quiet; then
            echo "No changes to commit."
          else
            git config --global user.name github-actions
            git config --global user.email actions@github.com
            git commit -am "Clean up"
            git push -u origin main
          fi
